### ISSUE TITLE
problem in ubuntu cli

### ISSUE THREAD

**Issue by rubber487** [balatamoghna/Whatsapp-Deku#2]
![Untitled](https://user-images.githubusercontent.com/47958483/94386198-4544c880-0171-11eb-8197-553c1dc0fc84.png)

I tried to install on ubuntu cli, but it looks like this

**Comment by balatamoghna** [comment]
You need to download Pedro's whatsapp-web.js from this repo: https://github.com/pedroslopez/whatsapp-web.js
Then simply place WABot.js into that folder(Or give the location of the index.js file from the mentioned repo) and run.
